# Advanced Navigation Spatial Dual Installation Alignment Data

Header header

# Alignment DCM (rotation matrix)
float64 alignment_dcm_0_0
float64 alignment_dcm_0_1
float64 alignment_dcm_0_2
float64 alignment_dcm_1_0
float64 alignment_dcm_1_1
float64 alignment_dcm_1_2
float64 alignment_dcm_2_0
float64 alignment_dcm_2_1
float64 alignment_dcm_2_2

# GNSS antenna offset
float64 gnss_offset_x
float64 gnss_offset_y
float64 gnss_offset_z

# Encoded wheel contact patch offset
float64 odometer_offset_x
float64 odometer_offset_y
float64 odometer_offset_z

# Offset local INS reporting frame. Unused
float64 external_data_offset_x
float64 external_data_offset_y
float64 external_data_offset_z